# **Numpy**

In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,6,5]) #arr is the ndarray object name
# print(arr) #print method 1

# for i in range(0,len(arr)): #Print method 2
#   print(arr[i])

for i in arr: #print method 3
  print(i)

1
2
3
6
5


In [ ]:
print(np.__version__)

1.23.5


In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
#0D array
arr1=np.array(42)
print(arr1)

42


In [ ]:
#1D array
arr2=np.array([12,23,45,122,45])
# for i in arr2: #print in ascending order
#   print(i)

for j in range((len(arr2)-1),-1,-1): #print in descending order
  print(arr2[j])

45
122
45
23
12


In [ ]:
#2D array
arr3=np.array([[1,2,3],[4,5,6]])

# for i in arr3: #print in ascending order
#   for j in i:
#     print(j,end=' ')
#   print()

# Print the arr3 in descending order
# for i in range((len(arr3) - 1), -1, -1):
#   for j in arr3[i][::-1]:
#     print(j, end=" ")
#   print()

#alternate way
for i in range((len(arr3) - 1), -1, -1):
  for j in range((len(arr3[i]) - 1), -1, -1):
    print(arr3[i][j], end=" ")
  print()

6 5 4 
3 2 1 


In [ ]:
#3D array
arr4=np.array([[[1,2,3],[4,5,6]],[[7,8,9]]])
# print(arr4.ndim)
# print arr4 in ascending order
for i in arr4:
  for j in i:
    for k in j:
      print(k,end=' ')
    print()

#print arr4 in descending order
# for i in range((len(arr4)-1),-1,-1):
#   for j in range((len(arr4[i])-1),-1,-1):
#     for k in arr4[i][j][::-1]:
#       print(k,end=' ')
#     print()

#print arr4 in descending order alternate
# for i in range((len(arr4)-1),-1,-1):
#   for j in range((len(arr4[i])-1),-1,-1):
#     for k in range((len(arr4[i][j])-1),-1,-1):
#       print(arr4[i][j][k],end=' ')
#     print()

1 2 3 
4 5 6 
7 8 9 


<ipython-input-10-1989c28c399e>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr4=np.array([[[1,2,3],[4,5,6]],[[7,8,9]]])


In [ ]:
#dimension set
import numpy as np
arr5=np.array([1,2,3,4,5],ndmin=5)
print(arr5.ndim)
print(arr5)

5
[[[[[1 2 3 4 5]]]]]


In [ ]:
#1D array indexing
arr6=np.array([1,3,4,5,6])
print(arr6[1]+arr6[3])
print(arr6[-1])

8
6


In [ ]:
#2D array indexing
arr3=np.array([[1,2,3],[4,5,6]])
print(arr3[0][2])
print(arr3[-1][-2])

3
5


In [ ]:
#3D array indexing
# arr4=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[11,12,13]]])
print(arr4[1][0][2])
print(arr4[-2][-1][-3])

9
4


**Numpy slicing**

In [ ]:
#Slicing 1D array
arr7=np.array([1,2,3,4,5,6,7,8])
print(arr7[1:5])
print(arr7[:4])
print(arr7[4:])
print(arr7[-6:-1])
print(arr7[1:6:2])
print(arr7[::2])

[2 3 4 5]
[1 2 3 4]
[5 6 7 8]
[3 4 5 6 7]
[2 4 6]
[1 3 5 7]


In [ ]:
#Slicing 2D array
arr8 = np.array([[1,2,3,4,5,6,7,8],[9,12,23,34,45,56,78,87]])
print(arr8[1,1:4])
print(arr8[0:2,5])

[12 23 34]
[ 6 56]


In [ ]:
arr8 = np.array([[1,2,3,4,5,6,7,8],[9,12,23,34,45,56,78,87]])
print(arr8[0:2,1:4])

[[ 2  3  4]
 [12 23 34]]


In [ ]:
print(arr8.dtype)

int64


In [ ]:
arr9=np.array(['Apple','Orange','Banana'])
print(arr9.dtype)

<U6


In [ ]:
# ar1=np.array(['1','2','3','a'],dtype='i4')
# print(ar1)
# print(arr.dtype)

#farhenhite to celcius or vice versa
# def func(x)

In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])
print(arr[0][1])

2nd element on 1st row:  2
2


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4],end=" ")

[[2 3 4]
 [7 8 9]] 

In [ ]:

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)
print(arr.ndim)
print(arr.dtype)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)
5
int64


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3,2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr2=arr.reshape(2,4)
print(arr2)
print(arr2.base)
print(arr.reshape(2, 4).base)


[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]


In [ ]:
import numpy as np
a=np.array(list(range(1,101)))
b=a.reshape(10,10)
for i in b:
  for b in i:
    print(b,end=" ")
  print()

1 2 3 4 5 6 7 8 9 10 
11 12 13 14 15 16 17 18 19 20 
21 22 23 24 25 26 27 28 29 30 
31 32 33 34 35 36 37 38 39 40 
41 42 43 44 45 46 47 48 49 50 
51 52 53 54 55 56 57 58 59 60 
61 62 63 64 65 66 67 68 69 70 
71 72 73 74 75 76 77 78 79 80 
81 82 83 84 85 86 87 88 89 90 
91 92 93 94 95 96 97 98 99 100 


In [ ]:
#3D array with unknown dimension
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#Converting multi dimensional array into 1
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [ ]:
#Converting multi dimensional array into 1
arr = np.array([[[1, 2, 3], [4, 5, 6]],[[1, 2, 3], [4, 5, 6]]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6 1 2 3 4 5 6]


In [ ]:
#Iterating 3D array one by one
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
# for i in arr:
#   for j in i:
#     for k in j:
#       print(k,end=" ")
#     print()

#print in reverse order
for i in range((len(arr)-1),-1,-1):
  for j in range((len(arr[i])-1),-1,-1):
    for k in range((len(arr[i][j])-1),-1,-1):
      print(arr[i][j][k],end=' ')
    print()



12 11 10 
9 8 7 
6 5 4 
3 2 1 


In [ ]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x,end=" ")
print()

1 2 3 4 5 6 7 8 


In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)
for i in newarr:
  print(i,end=" ")
print()

print(newarr[0])
print(newarr[1])
print(newarr[2])



[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2] [3 4] [5 6] 
[1 2]
[3 4]
[5 6]


In [ ]:
#Array searching
arr=np.array([1,2,3,4,5,56])
x=np.where(arr==4)
print(x)
y=np.where(arr%2==0)
print(y)

(array([3]),)
(array([1, 3, 5]),)


In [ ]:
#Print the numpy array in ascending and descending order
arr10=np.array([1,2,3,4,4,5,5,61,0,22,11,22])
newarrr=np.sort(arr10)
rev=newarrr[::-1]
print(rev)

[61 22 22 11  5  5  4  4  3  2  1  0]


In [ ]:
x = np.arange(5)
x+10

array([10, 11, 12, 13, 14])

In [ ]:
x=np.array([[2,3,4],[5,6,7]])
y=np.reshape(x,(3,2))
print(y)

[[2 3]
 [4 5]
 [6 7]]


In [ ]:
x=np.arange(6).reshape((3,2))
y=np.transpose(x)
print(y)

[[0 2 4]
 [1 3 5]]


In [ ]:
x=np.array([[2,3,4,8],[5,6,7,9]])
y=np.reshape(x,(4,-2))
print(y)

[[2 3]
 [4 8]
 [5 6]
 [7 9]]


# **OOP CONCEPT**

In [ ]:
#Class create using function syntax
class Alif():
  def __init__(self,p1,p2):
    self.p1=p1
    self.p2=p2
  def fun(self):
    print(self.p1)

In [ ]:
#print with object
class Animal():
  def __init__(self,name,color):
    self.name=name
    self.color=color
  def running(self):
    print(f'hey i am {self.name}. Now i am running.')
  def drinking(self):
    print(f'hey my color is {self.color}. Now i am drinking')
Tom=Animal('Cow','Brown')
Tom.running()
Tom.drinking()

hey i am Cow. Now i am running.
hey my color is Brown. Now i am drinking


In [ ]:
Bobby=Animal("Cat","Black")
Bobby.running()
Bobby.drinking()

hey i am Cat. Now i am running.
hey my color is Black. Now i am drinking


In [ ]:
#class object attribute
class Atom():
  species="Mammal"
  def __init__(this,name,colour):
    this.name=name
    this.colour=colour
  def running(this):
    print(f'Hey My name is {this.name}, I am running')
  def drinking(this):
    print(f'My color is {this.colour}, I am drinking')
Tam=Atom('Jerry','Brown')
Mick=Atom('Tom','Sky')
print('Class object attribute from Tam',Tam.species)
print('Class object attribute from Mick',Mick.species)
Tam.running()
Tam.drinking()
Mick.running()
Mick.drinking()

Class object attribute from Tam Mammal
Class object attribute from Mick Mammal
Hey My name is Jerry, I am running
My color is Brown, I am drinking
Hey My name is Tom, I am running
My color is Sky, I am drinking


In [ ]:
a = "Hello, World!"
print(a[1])

e


In [ ]:
a = "Hello"
b=",World! "
print(a.strip(b))

He


In [ ]:
fruits = ("apple", "banana", "cherry")
mytuple = fruits * 2

print(mytuple)

('apple', 'banana', 'cherry', 'apple', 'banana', 'cherry')


In [ ]:
w3

NameError: ignored